name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unittests
        run: npm test

  marked-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        marked-version: ['1.0.x', '2.0.x', '3.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install marked ${{ matrix.marked-version }}
        run: npm install --no-save marked@${{ matrix.marked-version }}
      - name: Run unittests
        run: npm test
